apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: todo-app:v1
          imagePullPolicy: Never          # ← use local minikube image
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_HOST
              value: mysql-svc            # ← direct value, simpler
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DB
              value: todos
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password