apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: todo-app
spec:
  type: ClusterIP        # Only accessible INSIDE the cluster
  selector:
    app: mysql           # Finds pods with label app=mysql
  ports:
    - port: 3306         # MySQL default port
      targetPort: 3306